//! Canonical event names. Table order follows the enum for constant-time rendering; parsing
//! names is only used at JSON boundaries, outside the typed event hot path.

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum Kind {
    AaActivate,
    AaGain,
    AaPotion,
    AaSpend,
    AllyPetLeader,
    BuffApply,
    BuffFade,
    BuffWearOff,
    CampAbort,
    CampStart,
    CastBegin,
    CastFizzle,
    CastInterrupted,
    CastResumed,
    Cc,
    CcWake,
    Charm,
    ClassUnlock,
    Coin,
    Consider,
    Damage,
    Death,
    ExpGain,
    Group,
    Heal,
    HealUnstated,
    IllusionFade,
    InstanceCreate,
    InvocationChange,
    ItemActivate,
    ItemMerge,
    ItemMergeFailed,
    ItemReceived,
    Level,
    Loot,
    Miss,
    Mitigation,
    Offer,
    OtherCastBegin,
    OutputFile,
    PetClaim,
    PetSay,
    PlayerDeath,
    PoisonCoat,
    PoisonDry,
    PoisonProc,
    Purchase,
    Resist,
    SelfWho,
    SessionStart,
    SkillUp,
    SpecialAttack,
    SpellEmote,
    SpellForget,
    SpellMemorize,
    SpellSet,
    StanceChange,
    TaskActivity,
    Trade,
    Uncharm,
    Unknown,
    Zone,
    // The fold's own, never written by a classifier.
    Epoch,
    OfflineGap,
    BuffExpired,
    /// A `kind` string this build does not know. Not reachable from [`crate::Parser`].
    #[default]
    Other,
}

const NAMES: [(Kind, &str); 66] = [
    (Kind::AaActivate, "aaActivate"),
    (Kind::AaGain, "aaGain"),
    (Kind::AaPotion, "aaPotion"),
    (Kind::AaSpend, "aaSpend"),
    (Kind::AllyPetLeader, "allyPetLeader"),
    (Kind::BuffApply, "buffApply"),
    (Kind::BuffFade, "buffFade"),
    (Kind::BuffWearOff, "buffWearOff"),
    (Kind::CampAbort, "campAbort"),
    (Kind::CampStart, "campStart"),
    (Kind::CastBegin, "castBegin"),
    (Kind::CastFizzle, "castFizzle"),
    (Kind::CastInterrupted, "castInterrupted"),
    (Kind::CastResumed, "castResumed"),
    (Kind::Cc, "cc"),
    (Kind::CcWake, "ccWake"),
    (Kind::Charm, "charm"),
    (Kind::ClassUnlock, "classUnlock"),
    (Kind::Coin, "coin"),
    (Kind::Consider, "consider"),
    (Kind::Damage, "damage"),
    (Kind::Death, "death"),
    (Kind::ExpGain, "expGain"),
    (Kind::Group, "group"),
    (Kind::Heal, "heal"),
    (Kind::HealUnstated, "healUnstated"),
    (Kind::IllusionFade, "illusionFade"),
    (Kind::InstanceCreate, "instanceCreate"),
    (Kind::InvocationChange, "invocationChange"),
    (Kind::ItemActivate, "itemActivate"),
    (Kind::ItemMerge, "itemMerge"),
    (Kind::ItemMergeFailed, "itemMergeFailed"),
    (Kind::ItemReceived, "itemReceived"),
    (Kind::Level, "level"),
    (Kind::Loot, "loot"),
    (Kind::Miss, "miss"),
    (Kind::Mitigation, "mitigation"),
    (Kind::Offer, "offer"),
    (Kind::OtherCastBegin, "otherCastBegin"),
    (Kind::OutputFile, "outputFile"),
    (Kind::PetClaim, "petClaim"),
    (Kind::PetSay, "petSay"),
    (Kind::PlayerDeath, "playerDeath"),
    (Kind::PoisonCoat, "poisonCoat"),
    (Kind::PoisonDry, "poisonDry"),
    (Kind::PoisonProc, "poisonProc"),
    (Kind::Purchase, "purchase"),
    (Kind::Resist, "resist"),
    (Kind::SelfWho, "selfWho"),
    (Kind::SessionStart, "sessionStart"),
    (Kind::SkillUp, "skillUp"),
    (Kind::SpecialAttack, "specialAttack"),
    (Kind::SpellEmote, "spellEmote"),
    (Kind::SpellForget, "spellForget"),
    (Kind::SpellMemorize, "spellMemorize"),
    (Kind::SpellSet, "spellSet"),
    (Kind::StanceChange, "stanceChange"),
    (Kind::TaskActivity, "taskActivity"),
    (Kind::Trade, "trade"),
    (Kind::Uncharm, "uncharm"),
    (Kind::Unknown, "unknown"),
    (Kind::Zone, "zone"),
    (Kind::Epoch, "epoch"),
    (Kind::OfflineGap, "offlineGap"),
    (Kind::BuffExpired, "buffExpired"),
    (Kind::Other, ""),
];

impl Kind {
    #[must_use]
    pub fn as_str(self) -> &'static str {
        NAMES[self as usize].1
    }

    #[must_use]
    pub fn parse(name: &str) -> Self {
        NAMES
            .iter()
            .find(|(_, text)| *text == name)
            .map_or(Self::Other, |(kind, _)| *kind)
    }

    pub const ALL: [Kind; 64] = [
        Kind::AaActivate,
        Kind::AaGain,
        Kind::AaPotion,
        Kind::AaSpend,
        Kind::AllyPetLeader,
        Kind::BuffApply,
        Kind::BuffFade,
        Kind::BuffWearOff,
        Kind::CampAbort,
        Kind::CampStart,
        Kind::CastBegin,
        Kind::CastFizzle,
        Kind::CastInterrupted,
        Kind::CastResumed,
        Kind::Cc,
        Kind::CcWake,
        Kind::Charm,
        Kind::ClassUnlock,
        Kind::Coin,
        Kind::Consider,
        Kind::Damage,
        Kind::Death,
        Kind::ExpGain,
        Kind::Group,
        Kind::Heal,
        Kind::HealUnstated,
        Kind::IllusionFade,
        Kind::InstanceCreate,
        Kind::InvocationChange,
        Kind::ItemActivate,
        Kind::ItemMerge,
        Kind::ItemMergeFailed,
        Kind::ItemReceived,
        Kind::Level,
        Kind::Loot,
        Kind::Miss,
        Kind::Mitigation,
        Kind::Offer,
        Kind::OtherCastBegin,
        Kind::OutputFile,
        Kind::PetClaim,
        Kind::PetSay,
        Kind::PlayerDeath,
        Kind::PoisonCoat,
        Kind::PoisonDry,
        Kind::PoisonProc,
        Kind::Purchase,
        Kind::Resist,
        Kind::SelfWho,
        Kind::SessionStart,
        Kind::SkillUp,
        Kind::SpecialAttack,
        Kind::SpellEmote,
        Kind::SpellForget,
        Kind::SpellMemorize,
        Kind::SpellSet,
        Kind::StanceChange,
        Kind::TaskActivity,
        Kind::Trade,
        Kind::Uncharm,
        Kind::Unknown,
        Kind::Zone,
        Kind::Epoch,
        Kind::OfflineGap,
    ];
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn names_follow_discriminants_and_every_kind_round_trips() {
        for (index, (kind, name)) in NAMES.iter().enumerate() {
            assert_eq!(*kind as usize, index);
            assert_eq!(kind.as_str(), *name);
            assert_eq!(Kind::parse(name), *kind);
        }
        assert_eq!(Kind::parse("unrecognized event"), Kind::Other);
        assert_eq!(Kind::TaskActivity.as_str(), "taskActivity");
    }
}
